name: Deploy frontend application

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Prepare the Docker Compose run
        run: |
          ls -l

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # Current directory, should contain the Dockerfile
          push: true
          tags: nuanwan04/frontend-app:latest

      - name: Copy Docker Compose file via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"  # Ensure this file exists
          target: "/home/ubuntu/frontend"  # Location on the server to copy the file

      - name: Deploy with Docker Compose via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend  # Change to the target directory where the docker-compose.yml is located
            docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker-compose down  # Stop any running containers
            docker-compose pull  # Pull the latest image from Docker Hub
            docker-compose up -d  # Start the containers in detached mode
            rm -rf /home/ubuntu/frontend  # Clean up the directory after deployment
