name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using GitHub Secrets (Docker Hub username and access token)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or access token stored in GitHub Secrets
      
      # Build and push Docker images for frontend and backend
      - name: Build and Push Docker Image for Frontend
        run: |
          docker build -t yourusername/frontend:$GITHUB_SHA ./frontend
          docker push yourusername/frontend:$GITHUB_SHA
      
      - name: Build and Push Docker Image for Backend
        run: |
          docker build -t yourusername/backend:$GITHUB_SHA ./backend
          docker push yourusername/backend:$GITHUB_SHA
      
      # Optionally, deploy to a server (like a VM, AWS, etc.) using Docker Compose or other tools
      - name: Deploy Application
        run: |
          # Example: Deploy with Docker Compose
          docker-compose -f docker-compose-prod.yml up -d
