name: Deploy frontend application

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: nuanwan04/234-deploylab-frontend:latest

      - name: Trigger DeepSource analysis
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DEEPSOURCE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "ref": "refs/heads/main",
                  "commit_sha": "${{ github.sha }}",
                  "repo_slug": "${{ github.repository }}"
                }' \
            https://deepsource.io/api/v1/repos/${{ github.repository }}/analysis/
